spec:
  inputs:
    java-version:
      default: '21'
      options: ['8', '17', '21']
    depoloy-environment:
      default: 'dev'
      options: ['dev', 'production']
---
stages:
  - mvn-build

cache:
  paths:
    - .m2/repository

maven build:
  image: maven:3.9.4-eclipse-temurin-21-alpine
  stage: mvn-build
  script:
    - mvn clean install
  when: manual